### ISSUE TITLE
Are there any recommendations on how to use MALAT1 threshold alongside existing tools for QC?

### ISSUE THREAD

**Issue by AmosFong1** [BaderLab/MALAT1_threshold#1]
Hello, I just read the pre-print and was interested in using this tool. I had a few follow up questions and requests for clarifications:

1. I imagine this technology would apply also to single-nuclei technologies such as 10X multiome, but I was wondering if you had any recommendations on whether parameters should be tweaked for this data type (i.e which parameters should be tuned or should the function be used with default settings when we expect a higher fraction of nuclei-associated transcripts)

2. Would this tool be useful in conjunction with a tool like SoupX which tries to “correct” gene expression values by estimating the average ambient RNA content using empty droplets? Or would the two tools conflict? 

3. Would you recommend running this tool before or after QC filtering? Before or after running a doublet detection algorithm?

**Comment by 14zac2** [comment]
Hi @AmosFong1 - great questions!

1. Because single-nuclei technologies are designed to capture nuclei, we rarely see low MALAT1 cells in these datasets. However, these do appear once in a blue moon. You are welcome to try the tool, but I don't think it's necessary based on what we've seen. If it's used, I don't think parameters would need to change.

2. It could be, yes! It depends on if you like the results from SoupX. If you were to use both tools, I would use ours first on the normalized expression matrix to get your final filtered set of cells. Following this, I would correct the expression matrix with SoupX if this is what you choose to do. Our tool has nothing to do with correcting ambient RNA expression, so real cells that also have ambient RNA captured with them will still look messy. Sad!

3. Great question! Based on my experience, I would recommend filtering with MALAT1 first, and then applying a doublet filter. Beyond that, I would check your UMI counts and mitochondrial levels, but getting rid of low MALAT1 cells may have gotten rid of most of your low quality cells.

I hope this helps and that this method works well for you! Please let us know if you have further questions or feedback.

Zoe
